@startuml
'https://plantuml.com/sequence-diagram

skinparam linetype polyline

participant "Client" as Client
participant "Controller" as Controller
participant "Authentication Enforcer" as AEE
participant "Authorisation Enforcer" as AOE
participant "Security Config" as SC
database "Database" as DB
participant "Account Table" as AT

== Authentication ==
Client -> Controller: login(accountDetails)
Activate Client
Activate Controller
Controller -> AEE: validateUser(accountDetails)
Activate AEE
AEE -> DB: findUsername(accountDetails)
Activate DB
DB -> AT: findAccountByUsername(username)
AT --> DB: Account{details}
DB --> AEE: Account{details}
Deactivate DB
AEE -> AEE: authenticate(accountDetails, retrievedDetails)
AEE --> Controller: confirmAuthenticated()
Deactivate AS
Controller --> Client: redirectToHomeJSP()
Deactivate AS
Deactivate Controller
Deactivate Client

== Authorisation ==
Client -> Controller: viewRestrictedPage()
Activate Client
Activate Controller
SSF -> Controller: interceptCall()
Activate SSF
SSF -> AS: checkRolePrivileges(accountDetails, requestedPage)
Activate AS
AS -> AS: runAuthorisationCheck(accountDetails, requestedPage)
note left: using .antMatcher()
AS --> SSF: confirmAuthorised
Deactivate AS
SSF --> Controller: permitRequest(requestedPage)
Deactivate SSF
Controller --> Client: loadPage(requestPage)
Deactivate Controller
Deactivate Client
@enduml