@startuml
'https://plantuml.com/sequence-diagram

skinparam linetype polyline

participant "Client" as Client
participant "SearchTimeslotController" as STC
participant "HealthCareProvider" as HCP
participant "Timeslot" as Timeslot
participant "TimeslotMapper" as TM
database "Database" as DB

== Lazy Load Initialisation ==
Client -> STC: searchTimeslots(vaccineType, postcode)
activate Client
activate STC
STC -> TM: findTimeslots(vaccineType, postcode)
activate TM
TM -> DB: findTimeslots(vaccineType, postcode)
DB --> TM: resultSet{Timeslots}
loop ResultSet{Timeslots}
    TM -> Timeslot: Timeslot(details)
    activate Timeslot
    Timeslot -> HCP: HealthCareProvider(null)
    activate HCP
    HCP --> Timeslot: HealthCareProvider{null}
    deactivate HCP
    Timeslot --> TM: Timeslot{details}
    deactivate Timeslot
end
TM --> STC: List<Timeslot{details}>
deactivate TM
STC --> Client: List<Timeslot{details}>
deactivate STC
deactivate Client
@enduml