@startuml
'https://plantuml.com/sequence-diagram

skinparam linetype polyline

participant "Client" as Client
participant "Controller" as Controller
participant "Domain Layer" as DL
participant "Data Mapper" as Mapper
participant "DB" as DB

== Creation Flow ==
Client -> Controller: requestObject{requestDetails}
activate Client
Controller -> Mapper: createRequest(requestDetails)
Mapper -> DB : databaseObject{requestDetails}
DB --> Mapper : databaseObject{responseDetails}
Mapper --> DL : responseObject{responseDetails}
DL --> Controller : responseObject{responseDetails}
Controller --> Client : responseObject{responseDetails}
deactivate Client

== Retrieval Flow ==
Client -> Controller: getRequest(objectID)
activate Client
Controller -> Mapper: getRequest(objectID)
Mapper -> DB : getObject(getRequest(objectID))
DB --> Mapper : databaseObject{details}
Mapper --> DL : responseObject{details}
DL --> Controller : responseObject{details}
Controller --> Client : responseObject{details}
deactivate Client
@enduml