@startuml
'https://plantuml.com/sequence-diagram

skinparam linetype polyline

participant "Client" as Client
participant "Controller" as Controller
participant "Spring Security Filter" as SSF
participant "AuthenticationService \n(Authentication and Authorisation Enforcer)" as AS
database "Database" as DB
participant "Account Table" as AT

== Authentication ==
Client -> Controller: login(accountDetails)
Activate Client
Activate Controller
Controller -> AS: validateUser(accountDetails)
Activate AS
AS -> DB: findUsername(accountDetails)
Activate DB
DB -> AT: findAccountByUsername(username)
AT --> DB: Account{details}
DB --> AS: Account{details}
Deactivate DB
AS -> AS: authenticate(accountDetails, retrievedDetails)
AS --> Controller: confirmAuthenticated()
Deactivate AS
Controller --> Client: redirectToHomeJSP()
Deactivate AS
Deactivate Controller
Deactivate Client

== Authorisation ==
Client -> Controller: viewRestrictedPage()
Activate Client
Activate Controller
SSF -> Controller: interceptCall()
Activate SSF
SSF -> AS: checkRolePrivileges(accountDetails, requestedPage)
Activate AS
AS -> AS: runAuthorisationCheck(accountDetails, requestedPage)
note left: using .antMatcher()
AS --> SSF: confirmAuthorised
Deactivate AS
SSF --> Controller: permitRequest(requestedPage)
Deactivate SSF
Controller --> Client: loadPage(requestPage)
Deactivate Controller
Deactivate Client
@enduml