@startuml

skinparam linetype polyline

participant "Client" as Client
participant "Controller" as C
participant “Domain Object" as O
participant "Data Mapper" as M
participant "Database" as DB

== Data Mapper ==
Client -> C: doPost(request, response)
activate C
C -> O: new Object()
activate O
O --> C: return object
deactivate O
C -> M: Mapper.insert(object)
deactivate C
activate M
M -> DB: insert()
activate DB
DB --> M: OK
deactivate M
deactivate DB

@enduml