@startuml
'https://plantuml.com/sequence-diagram

skinparam linetype polyline

participant "Client" as Client
participant "TimeslotController" as TC
participant "Timeslot Object" as TO
participant "Unit of Work" as UoW
participant "TimeslotMapper" as TM
database "Database" as DB



== Unit of Work ==
Client -> TC: doGet(request, response)
activate Client
activate TC
TC -> UoW: new UnitofWork()
activate UoW
UoW --> TC: return unitOfWork
TC --> Client: response(AddTimeslotJSP)

loop
Client -> TC: doPost(request, response)
TC -> TC: processRequest(timeslotDetails)
TC -> TO: new TimeSlot(timeslotDetails)
activate TO
TO --> TC: return timeslot
deactivate TO
TC -> UoW: registerNew(timeslot)
end

Client -> TC: doPost(request, response)
deactivate Client
TC -> UoW: commit()
deactivate TC

loop
UoW -> TM: insert(timeslot)
deactivate UoW
activate TM
TM -> DB: sqlQuery.execute()
activate DB
DB --> TM : OK
deactivate DB
end







@enduml