@startuml
'https://plantuml.com/use-case-diagram

left to right direction

actor :Administrator: as Admin
actor :Vaccine Recipients:  as VR
actor :Health Care Provider: as HCP

skinparam linetype polyline

package "COVID-19 Vaccine Booking System" {
    usecase (Filter by Type of\nVaccine Received) as (FTVR)
    usecase (Create Accounts) as (CA)
    usecase (Add Vaccine Types) as (AVT)
    usecase (View All Time-Slots) as (VATS)
    usecase (View All\nVaccine Recipients) as (VAVR)
    usecase (View All Users) as (VAU)
    usecase (Create Vaccine\nRecipient Account) as (CVRA)
    usecase (Create Health Care\nProvider Account) as (CHRA)
    usecase (Book a Time-Slot) as (BTS)
    usecase (Determine Eligibility) as (DE)
    usecase (Access Vaccination\nCertificate) as (AVC)
    usecase (Add Time-Slot Booking) as (ATS)
    usecase (Search for Time-Slots) as (STS)
    usecase (Search by Area) as (SA)
    usecase (Search by Health\nCare Provider) as (SHCA)
    usecase (Record a Completed Vaccination) as (RCV)
    usecase (Customize Time-Slot) as (CTS)
}

Admin --> (AVT)
Admin --> (VAU)
Admin --> (VATS)
Admin --> (CA)
(STS) <-- VR
(CVRA) <-- VR
(AVC) <-- VR
HCP --> (ATS)
HCP --> (RCV)
'(BTS) <-- VR

(CA) <|-- (CVRA)
(CA) <|-- (CHRA)
(SHCA) --|> (STS)
(SA) --|> (STS)

(VAVR) .> (VAU) : <<extend>>
(FTVR) .> (VAVR) : <<extend>>
(STS) <. (BTS) : <<extend>>
(BTS) .> (DE) : <<include>>
(ATS) <. (CTS) : <<extend>>

@enduml